// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "auth/domain/entity"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: ctx, userData
func (_m *Repo) AddAccount(ctx context.Context, userData entity.UserData) (int, error) {
	ret := _m.Called(ctx, userData)

	if len(ret) == 0 {
		panic("no return value specified for AddAccount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserData) (int, error)); ok {
		return rf(ctx, userData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserData) int); ok {
		r0 = rf(ctx, userData)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserData) error); ok {
		r1 = rf(ctx, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AddJunction provides a mock function with given fields: ctx, data
func (_m *Repo) AddJunction(ctx context.Context, data entity.JunctionData) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for AddJunction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.JunctionData) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCity provides a mock function with given fields: ctx, city
func (_m *Repo) GetCity(ctx context.Context, city string) (int, error) {
	ret := _m.Called(ctx, city)

	if len(ret) == 0 {
		panic("no return value specified for GetCity")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, city)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, city)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, city)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetId provides a mock function with given fields: ctx, id
func (_m *Repo) GetId(ctx context.Context, id int) (int, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (int, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNIK provides a mock function with given fields: ctx, nik
func (_m *Repo) GetNIK(ctx context.Context, nik string) (int, error) {
	ret := _m.Called(ctx, nik)

	if len(ret) == 0 {
		panic("no return value specified for GetNIK")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, nik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, nik)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPassword provides a mock function with given fields: ctx, id, nik
func (_m *Repo) GetPassword(ctx context.Context, id int, nik string) (string, error) {
	ret := _m.Called(ctx, id, nik)

	if len(ret) == 0 {
		panic("no return value specified for GetPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (string, error)); ok {
		return rf(ctx, id, nik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) string); ok {
		r0 = rf(ctx, id, nik)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, id, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProvince provides a mock function with given fields: ctx, province
func (_m *Repo) GetProvince(ctx context.Context, province string) (int, error) {
	ret := _m.Called(ctx, province)

	if len(ret) == 0 {
		panic("no return value specified for GetProvince")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, province)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, province)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, province)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RdsDel provides a mock function with given fields: ctx, key
func (_m *Repo) RdsDel(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for RdsDel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RdsGet provides a mock function with given fields: ctx, key, name
func (_m *Repo) RdsGet(ctx context.Context, key string, name string) (interface{}, error) {
	ret := _m.Called(ctx, key, name)

	if len(ret) == 0 {
		panic("no return value specified for RdsGet")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (interface{}, error)); ok {
		return rf(ctx, key, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) interface{}); ok {
		r0 = rf(ctx, key, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, key, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RdsSet provides a mock function with given fields: ctx, key, value, ttl
func (_m *Repo) RdsSet(ctx context.Context, key string, value string, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for RdsSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RdsTX provides a mock function with given fields: ctx, fn
func (_m *Repo) RdsTX(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RdsTX")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Setnx provides a mock function with given fields: ctx, key, value, ttl
func (_m *Repo) Setnx(ctx context.Context, key string, value string, ttl time.Duration) error {
	ret := _m.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Setnx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Transactions provides a mock function with given fields: ctx, fn
func (_m *Repo) Transactions(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Transactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
